### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mlazari**
In my Android emulator the popovers appear a little too high, but I don't think it's related to the dependency updates, since it's the same with the existing versions for me:

https://github.com/user-attachments/assets/7e775b57-5afc-4628-9543-4e283aa61e0b

### CODE REVIEW

**Comment by mlazari** [comment]
I think the issue I see on Android with the popover being displayed a little too high is related to this: https://github.com/SteffeyDev/react-native-popover-view/issues/156#issuecomment-1853813272

**Comment by mlazari** [comment]
Fixed the Android positioning with this commit: https://github.com/SteffeyDev/react-native-popover-view-test-app/pull/27/commits/ad3672b580332e300815fcc1a5b46d6fb381799b

**Comment by AdamGerthel** [comment]
I merged a couple of dependency PR's so yours is now in conflict. I'll make the updates myself and close this. It's the easiest atm.

**Comment by AdamGerthel** [comment]
> Fixed the Android positioning with this commit: [ad3672b](https://github.com/SteffeyDev/react-native-popover-view-test-app/commit/ad3672b580332e300815fcc1a5b46d6fb381799b)

This means that if the PR is applied the way it's currently written, it will be a breaking change

**Comment by mlazari** [comment]
> This means that if the PR is applied the way it's currently written, it will be a breaking change

Not sure if you were referring to commit https://github.com/SteffeyDev/react-native-popover-view-test-app/commit/ad3672b580332e300815fcc1a5b46d6fb381799b or something else. I think that commit is needed for ensuring that the popovers are displayed in the right position on every Android device in the test project, because apparently on some devices the status bar is translucent by default and some others - it isn't.

**Comment by AdamGerthel** [comment]
> > This means that if the PR is applied the way it's currently written, it will be a breaking change
> 
> Not sure if you were referring to commit [ad3672b](https://github.com/SteffeyDev/react-native-popover-view-test-app/commit/ad3672b580332e300815fcc1a5b46d6fb381799b) or something else. I think that commit is needed for ensuring that the popovers are displayed in the right position on every Android device in the test project, because apparently on some devices the status bar is translucent by default and some others - it isn't.

My point is just that if the only way to resolve the change in position on Android is through https://github.com/SteffeyDev/react-native-popover-view/pull/182, and that change potentially requires the end-user of the package to adjust the values passed to props, the it will be a breaking change.

**Comment by mlazari** [comment]
@AdamGerthel That's a completely different issue. The one I fixed in that commit is an existing issue - the Popover must be aware of the current `translucent` value of the StatusBar to position itself properly. Currently it assumes the StatusBar is translucent and adjusts for the StatusBar height (`verticalOffset={Platform.OS === "android" ? -StatusBar.currentHeight : 0}`, which I think could be replaced with `statusBarTranslucent={true}` and would have the same effect). On the device you're using the status bar happens to be translucent by default, so you don't see the issue, but in the emulator I was using the status bar was not translucent by default, so it was moved incorrectly up as you see in the video. I described that issue a year ago here: https://github.com/SteffeyDev/react-native-popover-view/issues/156#issuecomment-1853813272

**Comment by AdamGerthel** [comment]
I understand the problem, but I thought you meant that the PR is fine if we just change the props, but I see now that's not what you meant.

Are you suggesting that we change the props in the test app, as per your commit?

**Comment by mlazari** [comment]
> Are you suggesting that we change the props in the test app, as per your commit?

Yes, the apps already have to do that to ensure it's displaying correctly, so I don't think it's a breaking change.

**Comment by mlazari** [comment]
```
const statusBarTranslucent = false;
```

You can keep this to false, or change it to true, it should position the popover correctly in both cases.

**Comment by AdamGerthel** [comment]
Fixed

**Pull request closed without merging**
